### PR TITLE
Look for items with a permanent location

### LINKED ISSUE #1642: [sul-requests/folio-dev] NoMethodError: undefined method `callnumber' for nil:NilClass
## Backtrace

    line 9 of [PROJECT_ROOT]/app/views/application/_item_selector.html.erb: block in _app_views_application__item_selector_html_erb__3458773957260064665_40240
    line 2 of [PROJECT_ROOT]/app/views/application/_item_selector.html.erb: _app_views_application__item_selector_html_erb__3458773957260064665_40240
    line 6 of [PROJECT_ROOT]/app/views/requests/_form.html.erb: block in _app_views_requests__form_html_erb__1189377718974039696_40160

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49963/faults/98561049)

### PR DESCRIPTION
**Pull request by jcoyne**
This provides parity with how we find relevant items in Searchworks. Fixes #1642

### CODE REVIEW

File: app/models/folio/item.rb [hunk 1]
```diff
@@ -123,6 +127,7 @@ def self.from_hash(dyn)
                        dyn['chronology']].filter_map(&:presence).join(' '),
           public_note: dyn.fetch('notes').find { |note| note.dig('itemNoteType', 'name') == 'Public' }&.fetch('note'),
           effective_location: Location.from_hash(dyn.fetch('effectiveLocation')),
+          permanent_location_code: dyn.fetch('permanentLocation').fetch('code'),
```
Comment (cbeer) [inline app/models/folio/item.rb:130]: We also need to fall back on the holding's effective Location; we're no longer guaranteed an item-level permanent location.

Comment (jcoyne) [reply app/models/folio/item.rb]: I believe the fallback is complete.
