### PR TITLE
Move Illiad redirect to a before action filter and pass create via…

### LINKED ISSUE #309: Do not submit scan request to symphony if illiad fails

### PR DESCRIPTION
**Pull request by jkeck**
…GET as referrer.

Closes #309

### CODE REVIEW

File: app/controllers/scans_controller.rb [hunk 1]
```diff
@@ -2,6 +2,13 @@
 #  Controller to handle particular behaviors for Scan type requests
 ###
 class ScansController < RequestsController
+  # Redirect to the Illiad url if we have a POST request
+  # OR if not a POST request then check if the user can create a Scan object
+  # (e.g. a GET request redirected from a webauth challenge)
+  before_action only: :create do
+    redirect_to illiad_url if request.post? || can?(:create, Scan)
```
Comment (cbeer) [inline app/controllers/scans_controller.rb]: I'm having trouble grasping this condition. Why not just `can?(:create, Scan)`?

Comment (jkeck) [inline app/controllers/scans_controller.rb]: Switched this up to use a param that we pass in the URL we tell redirect Illiad back to us with.

**Comment by cbeer** [comment]
:+1:
