### PR TITLE
fix library hours for service points

### LINKED ISSUE #1887: [sul-requests/prod] NoMethodError: undefined method `[]' for nil:NilClass
When you request https://searchworks.stanford.edu/view/in00000010636 and change to Spec it says Content missing

## Backtrace

    line 29 of [PROJECT_ROOT]/app/models/library_hours.rb: library_slug
    line 21 of [PROJECT_ROOT]/app/models/library_hours.rb: library_hours
    line 15 of [PROJECT_ROOT]/app/models/library_hours.rb: next_business_day

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49963/faults/100676486)

### PR DESCRIPTION
**Pull request by dnoneill**
closes #1887

### CODE REVIEW

File: spec/models/library_hours_spec.rb [hunk 1]
```diff
@@ -22,4 +22,22 @@
       end
     end
   end
+
+  describe '#library_slug' do
```
Comment (jcoyne) [inline spec/models/library_hours_spec.rb:26]: Should there be a test for `location_map` for the context which you are fixing?

Comment (dnoneill) [reply spec/models/library_hours_spec.rb:26]: This is basically testing this. Location map returns a hash which is why I am using library_slug, because library_slug is just pulling a field from location_hash.

**Comment by dnoneill** [comment]
@jcoyne you are suggesting something like this?

def origin_library_next_business_day
    from = Settings.libraries[from] ? from : Folio::Types.service_points.find_by(code: from)&.library&.code
    LibraryHours.new(from).next_business_day(as_of, business_days_later)
  end

  def destination_library_hours_next_business_day_after_delivery
    to = Settings.libraries[to] ? to : Folio::Types.service_points.find_by(code: to)&.library&.code
    LibraryHours.new(to).next_business_day(origin_library_next_business_day)
  end
  
  Or are you suggesting I change it all the way up in?
  
  @to =  Settings.libraries[to] ? to : Folio::Types.service_points.find_by(code: to)&.library&.code
  @from = Settings.libraries[from] ? from : Folio::Types.service_points.find_by(code: from)&.library&.code
  
  Because I think this way might be probematic.

**Comment by jcoyne** [comment]
Yes, I was thinking the former.  I only think it needs to be in `destination_library_hours_next_business_day_after_delivery` not in `origin_library_next_business_day`, right?

**Comment by dnoneill** [comment]
That makes sense. yeah.

**Review by jcoyne — APPROVED** [review]
